version: "1.0"
info:
  model: int-scaffold
packages:
- name: FLOW_TEST_30_08Project
  gitServerName: poanTestGit
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
